- name: Summer Forever
  logo: summerforever.svg
- name: Windmill
  logo: windmill.svg
- name: Decision Computing
  logo: decisioncomputing.svg
- name: locals.com
  logo: locals.svg
- name: Summation
  logo: summation.svg
- name: Media Cluster Norway
  logo: mediaclusternorway.svg
- name: Ascend.io
  logo: ascend.svg
- name: Complexity Science Hub Vienna
  logo: complexity.svg
- name: PostHog
  logo: posthog.svg
- name: Sliplane
  logo: sliplane.svg
- name: Austrian Supply Chain Intelligence Institute
  logo: ascii.svg
